name: flutterwright_driver
description: A remote agent for Flutterwright to simulate production-level user interactions and text extractions over Dart VM Service.
version: 0.0.1
# publish_to: 'none'
homepage: https://github.com/zuukabrasil/flutterwright

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0